### ISSUE TITLE
Question about embedding Ogmo Editor assets

### ISSUE THREAD

**Issue by as3boyan** [HaxeFlixel/flixel-docs#118]
https://github.com/HaxeFlixel/flixel-docs/blob/master/documentation/04_tutorials/13-part-xii-multiple-platforms.html.md

```xml
<assets path="assets/data" include="*.oel|*.oep" />
```

I don't get it why we may need `"*.oep"`? It's a Ogmo Editor project file, and I don't think that `FlxOgmoLoader` needs it.

**Comment by as3boyan** [comment]
BTW, RPG tutorial is great!

**Comment by Gama11** [comment]
Good point, the .oep file isn't being used.
