### ISSUE TITLE
Tutorial showing HTML tags are showing in code examples

### ISSUE THREAD

**Issue by flabbyfabby** [HaxeFlixel/flixel-docs#119]
In the tutorial on some of the pages the HTML tags are showing in the code examples.

http://haxeflixel.com/documentation/part-v-tiles-maps-and-collisions/
![untitled](https://cloud.githubusercontent.com/assets/6450195/6992610/2e240936-dad0-11e4-8bcd-2953dfed1a9a.png)
Shows " < strong > " and " < / strong > " instead of " __ ".

http://haxeflixel.com/documentation/part-viii-enemies-and-basic-ai/
![untitled2](https://cloud.githubusercontent.com/assets/6450195/6992594/4fbededc-dacf-11e4-943c-b3885098bfb9.png)
Shows " < em > " and " < / em > " instead of multiply. Also shows " < br > ".

**Comment by Gama11** [comment]
Fixed by #125.
