### ISSUE TITLE
Tutorial missing information

### ISSUE THREAD

**Issue by flabbyfabby** [HaxeFlixel/flixel-docs#120]
Just a few things that were missing in the tutorial but were shown in the source.

http://haxeflixel.com/documentation/part-ix-ui-and-combat/

At stage 4 there is nothing saying about the ***checkEnemyVision()*** function needing to have the for loop inside of it.

Nowhere did it say to add ***using flixel.util.FlxSpriteUtil;*** to the top of the ***PlayState*** or ***Enemy*** classes so that flickering could work.

**Comment by SeiferTim** [comment]
@flabbyfabby can you tell me what loop in `checkEnemyVision` you are referring to? Thanks.
