### ISSUE TITLE
Two things on coding style

### ISSUE THREAD

**Issue by xerosugar** [HaxeFlixel/flixel-docs#122]
1) On the topic of Spacing; should it mention something about blank lines? For example: Do use blank lines to group things that are related, or do similar things, like variable declarations. And, do not use blank lines if the previous/next line only contains a single opening/closing parenthesis etc.

2) When is it okay to omit parentheses in if-statements?

**Comment by Gama11** [comment]
1) Not sure, there are a lot of different cases here and some are very difficult to define clearly. I doubt the flixel codebase is very consistent about this as is.

2) I think it's fine to omit them whenever possible / they're optional. I don't think flixel is consistent about this either though, some people prefer adding paretheses for readability.
