### ISSUE TITLE
[Enhancement] Add a Ogmo editor sample file to tutorial

### ISSUE THREAD

**Issue by benwaah** [HaxeFlixel/flixel-docs#142]
Hi,

Following the tutorial with no access to a Windows machine, step 5 is blocking as it requires learner to create an Ogmo map to be loaded in the game. Yet Ogmo editor is a Windows only application.

It would be great to add link to a sample file for non-Windows users to be able to go through the complete tutorial.

Here is a link to [part 5 of the tutorial](flixel-docs/documentation/04_tutorials/06-part-v-tiles-maps-and-collisions.html.md) for reference.

**Comment by Gama11** [comment]
The complete source code of the finished tutorial game is [available in flixel-demos](https://github.com/HaxeFlixel/flixel-demos/tree/1.1.2/Tutorials/TurnBasedRPG) - [including the ogmo map file](https://github.com/HaxeFlixel/flixel-demos/tree/1.1.2/Tutorials/TurnBasedRPG/assets/data).

**Comment by benwaah** [comment]
My bad, I should've found the link to the full source in the conclusion part.

I still believe a direct link in the section itself would be a plus though, so I've just created a [pull request](https://github.com/HaxeFlixel/flixel-docs/pull/143) for this

**Comment by Gama11** [comment]
See https://github.com/HaxeFlixel/flixel-docs/pull/143#issuecomment-174342550.
