### ISSUE TITLE
Reference to inexistent code in HaxeFlixel Tutorial

### ISSUE THREAD

**Issue by JefePapaya** [HaxeFlixel/flixel-docs#155]
On section 11 of the Turn Based RPG Tutorial, **Game Over Menu** (http://haxeflixel.com/documentation/game-over-menu/), there is a reference to an inexistent code.

On line 7 of this [file](https://github.com/HaxeFlixel/flixel-docs/blob/master/documentation/01_tutorial/12-11-game-over-menu.html.md) it says 
> 1. The first thing we want to do is stop our `CombatHUD` from stopping once the player has been defeated. So in `doneResultsIn()`, remove the `if (outcome != DEFEAT)` statement.

There's no such `if (outcome != DEFEAT)` statement in [`CombatHUD.hx`](https://github.com/HaxeFlixel/flixel-demos/blob/master/Tutorials/TurnBasedRPG/source/CombatHUD.hx).
Maybe the text is outadated and this existed in a previous version.

**Comment by Gama11** [comment]
Are you sure this wasn't added in a previous step somewhere? It's not surprising that `CombatHUD.hx` in flixel-demos doesn't have that line, that's the final version of the tutorial game, and it does say to remove that line in that step. :)

**Comment by JefePapaya** [comment]
Well, I may have misread something, but this same file is referenced from the [previous step](http://haxeflixel.com/documentation/ui-and-combat/).
This file isn't modified in the previous step, so it still seems wrong.
I've noticed some other things off. I hope getting better with HaxeFlixel and then making pull requests.

**Comment by JefePapaya** [comment]
I think the problem is asking the reader to use the final `CombatHUD` file, instead of giving they a version to modify accordingly. I just found another inconsistency with this, moving forward to [section 13](http://haxeflixel.com/documentation/multiple-platforms/), the tutorial instructs to add a code that was already in the file.
I hope you have the time to take a look. It's easier to get the picture if you look from section 10 to 13.

**Comment by KosnIre** [comment]
> There's no such if (outcome != DEFEAT) statement in CombatHUD.hx.
Maybe the text is outadated and this existed in a previous version.

I just noticed this too when I was following along. It's not a big issue, but I agree that it should be changed. Whether that means removing the text, or creating a partially-complete CombatHUD file<sup>1</sup>, I'm not sure.

<sup>1</sup>This might help with #171 as well.
