### ISSUE TITLE
Better sound doc on cheat sheet

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel-docs#156]
Info like that found in https://github.com/HaxeFlixel/flixel/issues/524 would be useful on the cheat sheet, given that googling "haxeflixel play sound" returns the cheat sheet as the top result currently.  I.e. that for music, you need OGGs for everything but Flash, and MP3s of a very specific kind only on Flash (and you'll need a compiler directive); and that for sound effects you should use WAV for everything (although I thought I had read in an openfl thread recently, that even WAV isn't universally supported...I think in HTML5 renderers, or something...)

Also that you needn't name each sound asset in your project.xml just like you needn't name every image asset, that's helpful to know, but between the cheat sheet, HaxeFlixel's project.xml and the original openfl project.xml page, you would get the idea that sounds are somehow special and each one requires a line in your project.xml, unlike images, which can be automatically included all with one line.

Depending on your target platform and what sound format you first try, the above combination of factors can make for quite a hurdle for someone trying to get set up to play sounds in their game.  (And while the demos are a good place to look--although I think it should be legit to google something as a starting point--they're also inconsistent.  E.g. NeonVector has mp3's in its sounds assets directory...)

**Comment by Gama11** [comment]
Pull request? :)
