### ISSUE TITLE
Tutorial Part 11: Missing assets referenced in OptionsState class

### ISSUE THREAD

**Issue by KosnIre** [HaxeFlixel/flixel-docs#185]
The steps in [Part 11 of the tutorial](http://haxeflixel.com/documentation/game-over-menu/) have you download the completed `OptionsState.hx` file. This file uses 2 assets that have not previously been mentioned in the tutorial: `button.png` and `select.wav`

```
source/OptionsState.hx:45: characters 29-51 : Class<AssetPaths> has no field button__png
source/OptionsState.hx:46: characters 46-68 : Class<AssetPaths> has no field select__wav
source/OptionsState.hx:50: characters 27-49 : Class<AssetPaths> has no field button__png
source/OptionsState.hx:51: characters 44-66 : Class<AssetPaths> has no field select__wav
source/OptionsState.hx:73: characters 45-67 : Class<AssetPaths> has no field select__wav
source/OptionsState.hx:77: characters 40-62 : Class<AssetPaths> has no field select__wav
Build halted with errors.
```

A clever developer will go find these assets in [the demo's assets folder on github](https://github.com/HaxeFlixel/flixel-demos/tree/master/Tutorials/TurnBasedRPG/assets) (or an ambitious developer would make their own), but it should probably be addressed in the tutorial itself.

**Comment by KosnIre** [comment]
Also, the issue of the sound file is somewhat related to #171. This is probably further reasoning for switching the order of the Sections.

I hope I'm not being annoying with these. I'm trying to catalog what I find, because I know it's difficult to maintain newbie guides. I plan to go back later and help with fixing it.

**Comment by Gama11** [comment]
>I hope I'm not being annoying with these

No, this is great - please continue! :)

**Comment by Gama11** [comment]
There used to be a repo with a branch for each step of the tutorial. This became a maintainability issue when updating the tutorial though (you'd have to update ~12 branches in the worst case when you change something at the start), so now there's just the final code in flixel-demos.

Presumably, the links to the full files for `OptionsState` and `CombatHUD` went to their respective branches and were correct at to some point.

**Comment by KosnIre** [comment]
So, do those old repos still exist somewhere? Is it worth digging up those 2 files?

**Comment by Gama11** [comment]
Maybe, I don't have it anymore though. Maybe @SeiferTim does. But it might make more sense to restructure things a bit anyway so we don't need two different versions of the files... (which would as you pointed out become a maintainability issue).
