### ISSUE TITLE
Tutorial Chapter 12 mentions setupGame function

### ISSUE THREAD

**Issue by KosnIre** [HaxeFlixel/flixel-docs#187]
The [Tutorial Chapter 12 Sound and Music](http://haxeflixel.com/documentation/sound-and-music/) mentions a function called `setupGame`.

> we're going to make it start playing outside of our states when we setup our game. In the **setupGame function**, after our volume-setting code, add:

This function is not mentioned anywhere else in the Tutorial and I dont find it in the HaxeFlixel code either. I believe it was a helper function that was possibly used in a previous version of the Tutorial, but is no longer needed. [Chapter 13](http://haxeflixel.com/documentation/multiple-platforms/) edits this same area of the code (see Step 4 there) and does not talk about a `setupGame` function there.

**Comment by Gama11** [comment]
`setupGame()` used to be part of `Main.hx` of the template.

**Comment by Gama11** [comment]
That doesn't match the source in flixel-demos though, the music starts playing in `MenuState` there...

**Comment by KosnIre** [comment]
Ok yes, a693b04 works quite nicely, and moving it to `MenuState` also fixes the issue where the music would play over the HaxeFlixel logo in a release build.

One more adjustment though—[13 Multiple Platforms](http://haxeflixel.com/documentation/multiple-platforms/) says:

> 4\. Now that we have different versions of our music, we need to make sure we play the right version. In **Main.hx**, replace the line where we start playing our music with:

...where `Main.hx` now needs to be `MenuState.hx`.

**Comment by Gama11** [comment]
Man, so easy for things to get out of sync. Thanks, fixed! :)

**Comment by KosnIre** [comment]
No problem, that's why it's nice to have multiple eyes on a project :)
