### ISSUE TITLE
Cheat Sheet is not up to date regarding drawing on canvas

### ISSUE THREAD

**Issue by Alvalol** [HaxeFlixel/flixel-docs#193]
http://haxeflixel.com/documentation/cheat-sheet/

The cheat sheet is not up to date with flixel.

proposed changes here https://github.com/HaxeFlixel/flixel-docs/compare/master...Alvalol:patch-1

**Comment by Gama11** [comment]
It is up to date. You're missing `using flixel.util.FlxSpriteUtil;` which is mentioned a bit earlier on the page.
