### ISSUE TITLE
Add Docs to load a map from tiled

### ISSUE THREAD

**Issue by lucas-aragno** [HaxeFlixel/flixel-docs#196]
http://haxeflixel.com/documentation/loading-the-tilemap/ I'm trying to get back into flixel I remember that this page was showing how to load a tilemap from tiled instead of whatever that program is. And the demo code seems to be to complex for this tutorial, there is any place where I can reach those docs?

**Comment by Gama11** [comment]
I'm not sure what you mean. That page still has instructions for Tiled.

**Comment by lucas-aragno** [comment]
Could you send me a link?

**Comment by Gama11** [comment]
I was talking about the page you linked to yourself (http://haxeflixel.com/documentation/loading-the-tilemap/).

**Comment by starry-abyss** [comment]
There is a simpler approach if you don't need complex features of Tiled.
Do everything in tile layers and export them to CSV.
