### ISSUE TITLE
Install Flixel - Typo and further info could be added

### ISSUE THREAD

**Issue by null9** [HaxeFlixel/flixel-docs#197]
The following paragraph has a typo:

> To compile to desktop and mobile targets, you have to make sure you have run their respective lime setup commands are completed, each are specified in the OpenFL platform docs.

It should probably read something like:

> To compile to desktop and mobile targets, you have to make sure you have run the respective lime setup commands. Each are specified in the OpenFL platform docs.

In addition, it is not immediately obvious upon visiting the OpenFL pages exactly what commands are required. It may be worthwhile adding them in short on this page (I actually ended up running different commands to the ones specified on the OpenFL page, choosing to use "lime setup windows" etc. instead).

**Comment by Hasufel** [comment]
Thank you.
