### ISSUE TITLE
please stop stealing focus

### ISSUE THREAD

**Issue by raould** [HaxeFlixel/flixel-docs#198]
e.g. in the APIs I click outside the search box and then press the space bar to try to scroll the page. But somehow the web page has recaptured my mouse focus, making it on the text search field again, and the spacebar doesn't scroll it just inserts a space in there. this is driving me kind of utterly bat crazy.
ubuntu 14.04 lts intel/amd 64bit
firefox 50.1.0
on pages like e.g. http://api.haxeflixel.com/flixel/index.html

on ditto any keys at all?! apparently?! like page down, or down arrow?! :-(

**Comment by Gama11** [comment]
See https://github.com/HaxeFoundation/dox/issues/208. I guess this would be fixed by a Dox update.
