### ISSUE TITLE
API docs for VCR frontend are incomplete

### ISSUE THREAD

**Issue by Cor-cor** [HaxeFlixel/flixel-docs#201]
Currently the page: http://api.haxeflixel.com/flixel/system/frontEnds/VCRFrontEnd.html has only a couple of variables and methods described while there are clearly more of them in the source code: https://github.com/HaxeFlixel/flixel/blob/master/flixel/system/frontEnds/VCRFrontEnd.hx

Just a thought: may it be related to having other parts of API under `FLX_RECORD` define?

**Comment by Gama11** [comment]
That's exactly right. We don't define `FLX_RECORD` here at the moment:

https://github.com/HaxeFlixel/flixel-docs/blob/master/api/dox-gen/xml/project.xml

Should be safe to change though, thanks for noticing!

**Comment by Gama11** [comment]
Alright, should be good now. If the fields don't show up right away, you may need to `Shift+F5` the page.
