### ISSUE TITLE
Haxeflixel clean uses the ls command

### ISSUE THREAD

**Issue by Starmann** [HaxeFlixel/flixel-docs#217]
Parsing ls is considered a shell scripting anti-pattern. It's recommended by most advanced shell scripters to use the find command instead.

**Comment by Gama11** [comment]
I guess you mean https://github.com/HaxeFlixel/flixel-docs/blob/master/api/dox-gen/clean.hxml?

I'm not really sure why using using `ls` like would be an issue (appears to work fine), and it's mostly for "internal use" (for me to regenerate the API docs). Feel free to submit a PR if you want.
