### ISSUE TITLE
Haxe Constraints documentation doesn't exist

### ISSUE THREAD

**Issue by Starmann** [HaxeFlixel/flixel-docs#218]
On the Haxe documentation website, the entry for [haxe.constaints.Constructible](https://api.haxe.org/haxe/Constructible.html) links to the import [haxe.constraints](https://api.haxe.org/haxe/Constraints.html) which doesn't currently exist, causing a 404.

**Comment by Gama11** [comment]
This is not the correct repository for issues with api.haxe.org, only api.haxeflixel.com. See here, the "Something on api.haxe.org" section:

https://github.com/HaxeFoundation/haxe/blob/development/CONTRIBUTING.md#is-this-the-right-repository-to-report-the-issue

**Comment by Starmann** [comment]
@Gama11 
Apologies. I understand that haxe-flixel is the wrong repository to post this to. I had meant to post this on Haxe's docs but ended up here instead of there.
