### ISSUE TITLE
Tutorial Part 10 - UI and Combat drawRect does not exist

### ISSUE THREAD

**Issue by NickersWeb** [HaxeFlixel/flixel-docs#239]
FlxSprite does not contain drawRect.
flixel version: 4.7.0

**Comment by NickersWeb** [comment]
I think my intellisense was just taking a crap on me. Potentially ignore.

**Comment by Gama11** [comment]
It does indeed not contain that, it's a [static extension](https://haxe.org/manual/lf-static-extension.html) from `flixel.util.FlxSpriteUtil`, so you need the following for it to be available:

```haxe
using flixel.util.FlxSpriteUtil;
```
