### ISSUE TITLE
Remove HaxeDevelop page?

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/flixel-docs#270]
I think everyone uses VSCode nowadays! And HaxeDevelop is completely unmaintained! I feel like it cleans things up a bit, and makes things feel less OLD to have recommendations to deprecated and unmaintained software!

**Comment by Geokureli** [comment]
makes sense!

**Comment by ninjamuffin99** [comment]
I wknder what the Sumbline Text or IntelliJ usage is, maybe can toss recommendations towards those
