### ISSUE TITLE
Dedicated section for external tutorials?

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/flixel-docs#273]
OpenFL has a cute little section for community / external tutorials: https://www.openfl.org/learn/haxelib/tutorials/

So I think it might be nice to have a central place for links !

example... ohsat games has some interesting looking tutorials! https://www.ohsat.com/tutorial/

Along with that, there's some video tutorials floatin around by Richard Oliver Bray. Might be nice to have something like that for further learning

**Comment by Geokureli** [comment]
yeah we should add Tutorials to [Resources](https://haxeflixel.com/documentation/resources/)

**Comment by ninjamuffin99** [comment]
closed with #280 merge!
