### ISSUE TITLE
Suggestion: FLX_DEBUG_STRICT

### ISSUE THREAD

**Issue by chosencharacters** [HaxeFlixel/flixel-docs#284]
I keep adding this flag to my own version of flixel but FLX_DEBUG_STRICT is a flag that causes Logs (specifically animation logs) to throw an error instead of logging. This is useful for in-dev projects that have tons of animations and would rather have a stack trace the moment an issue happens.

Example lines
https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/animation/FlxAnimationController.hx#L203
https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/animation/FlxAnimationController.hx#L234
https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/animation/FlxAnimationController.hx#L237
https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/animation/FlxAnimationController.hx#L269

(and any other line where a log is)

example change for L203 would be

```
#if FLX_DEBUG_STRICT
throw 'Could not append frames above ${numFrames - 1} to animation: "$name"'
#else
FlxG.log.warn('Could not append frames above ${numFrames - 1} to animation: "$name"');
#end
```

(You could alternatively add it to the actual Flixel logger)

https://github.com/HaxeFlixel/flixel/blob/7e7eb5cfe31e2ccbdc49561ca90b7d9108d3d2c3/flixel/system/frontEnds/LogFrontEnd.hx#L27

```
#if FLX_DEBUG_STRICT
throw data;
#else
advanced(data, LogStyle.WARNING, true);
#end
```

**Comment by Geokureli** [comment]
You can already change any log style to throw an exception via:
```hx
LogStyle.ERROR.throwException = true;
```
then whenever you call `FlxG.log.error` or `FlxG.log.advance(data, LogStyle.ERROR)` it'll throw an exception

**Comment by Geokureli** [comment]
@chosencharacters can this be closed, given the proposed workaround?

**Comment by chosencharacters** [comment]
Yes and with great shame that it opened in the first place :(

**Comment by Geokureli** [comment]
No shame, Flixel's logging tools are widely not well-known, and it's hard to teach them via demos and snippets

**Comment by chosencharacters** [comment]
Too late shame has already been taken
