### ISSUE TITLE
Adding the external-resources list to flixel-docs

### ISSUE THREAD

**Issue by sruloart** [HaxeFlixel/flixel-docs#85]
[here](https://github.com/sruloart/External-Resources-for-HaxeFlixel/blob/master/HaxeFlixel%27s%20Resources.md)
Question is, how exactly? 
I feel like the list should be split into a few pages:
______________________________________
- native-extensions.md will be replaced with all the native entries, and maybe someday, the explanations that I intended to add about how to make and use them.
- There will be a new external-services.md that will hold the services entries.
- There will be a new games-sources.md that will hold the games-sources entries.
- There will be a new flixel-extensions.md that will hold the non-formal Flixel libraries entries.

I'm not sure about the numbering order yet, as things change quite quickly around here.

Now, maybe you prefer the list to stay outside of the documents, or have a different structure for entries, or anything at all, I just want to make sure I'm sending the list in the best possible way.

**Comment by Gama11** [comment]
I guess this can be closed since the corresponding PR (#90) has been closed as well.
