### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by thely** [HaxeFlixel/flixel-docs#89]
Note: these are about the tutorial pages in the documentation.

* Underscores are appearing as `<em>` and `<strong>` tags. All lines declaring image or Ogmo map files are appearing as `coin<strong>png` instead of `coin__png`. The underscore in Coin.hx's `finishKill()` function is also appearing this way. Random `<br />` tags are also appearing sometimes, but this is far less confusing than missing underscores.
* In part IX, `FlxGroup` is imported for HUD.hx instead of `FlxTypedGroup`, and the health graphic is not on the page as previous graphics were.
* `changeEnemy()` is never added to Enemy.hx in the tutorial.

**Comment by Gama11** [comment]
Fixed by #125.
